spring:
  jpa:
    properties:
      hibernate:
        default_schema: ping
  datasource:
    driver-class-name: org.postgresql.Driver
    #url: ${JDBC_DATABASE_URL}
    #username: ${JDBC_DATABASE_USERNAME}
    #password: ${JDBC_DATABASE_PASSWORD}
    password: admin
    url: jdbc:postgresql://localhost:5432/pingchat
    username: postgres
#    hikari:
#      validation-timeout: '3000'
#      connection-timeout: '30000'
#      data-source-properties:
#        maintainTimeStats: 'false'
#        useServerPrepStmts: 'true'
#        cacheResultSetMetadata: 'true'
#        cacheServerConfiguration: 'true'
#        cachePrepStmts: 'true'
#        rewriteBatchedStatements: 'true'
#        prepStmtCacheSqlLimit: '2048'
#        elideSetAutoCommits: 'true'
#        useLocalSessionState: 'true'
#        prepStmtCacheSize: '250'
#      initialization-fail-timeout: '2000'
#      idle-timeout: '600000'
#      maximum-pool-size: '40'
#      isolate-internal-queries: 'true'
#      max-lifetime: '1800000'
#      connection-test-query: SELECT 1
#      minimum-idle: '8'

